packages:
  - test

configDependencies:
  "@obusk/pnpm-plugin-defaults": 0.2.0+sha512-3oufTLQAL1SDdQ9iA5hLRnZjnBnU9uIEOBcwCKRtS+F6NyJphTq6RMIpaZgostZjQRHUaNbGSg6B2gn91drCSQ==

hoistPattern:
  - "@next/eslint-plugin-next"
  - eslint-plugin-react-hooks

ignoredBuiltDependencies:
  - sharp

minimumReleaseAgeExclude:
  - ts-api-utils@2.4.0

onlyBuiltDependencies:
  - simple-git-hooks@2.13.1
  - unrs-resolver@1.11.1

overrides:
  "@eslint/core": 0.17.0

trustPolicyExclude:
  - eslint-import-resolver-typescript@3.10.1
  - semver@6.3.1
  - tailwindcss@3.4.18
