configDependencies:
  "@obusk/pnpm-defaults": 0.0.2-4+sha512-AZ6g/lhp9+32T5ub8OOS5hRRYej/kvCcUF/tz9Kdea0JkQ0PakrrbWg7LSM7gqFot5IjNwVEuPkEzFj9Oga3yQ==

packages:
  - "test"

hoistPattern:
  - "@next/eslint-plugin-next"
  - "eslint-plugin-react-hooks"

onlyBuiltDependencies:
  - simple-git-hooks@2.13.1
  - unrs-resolver@1.11.1

ignoredBuiltDependencies:
  - sharp
