packages:
  - test

configDependencies:
  "@obusk/pnpm-plugin-defaults": 0.1.0+sha512-vsCchpE+K6g67YdDYYBCVQQFpfVFuVV423CCBbUEBm7FmWg/MI0Keuhkb6bjWpWaITE1PMSmcsrXbHv9FPFloA==

hoistPattern:
  - "@next/eslint-plugin-next"
  - eslint-plugin-react-hooks

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - simple-git-hooks@2.13.1
  - unrs-resolver@1.11.1

trustPolicyExclude:
  - eslint-import-resolver-typescript@3.10.1
  - semver@6.3.1
  - tailwindcss@3.4.18

# Add patches to specific packages
# https://pnpm.io/settings#patcheddependencies
patchedDependencies:
  # Needed until https://github.com/vercel/next.js/issues/85379 is closed
  eslint-config-next@16.0.1: "patches/eslint-config-next@16.0.1.patch"
