packages:
  - test

configDependencies:
  "@obusk/pnpm-plugin-defaults": 0.3.0+sha512-Vc6B0IfZgB+ydRh0eYpmxV7eCEC5fjDcKX+WrpSd3NiIaFS7yLrXRaWVSoIOLvAYIKbcsYXUa+ZFCf5zVw3nSw==

hoistPattern:
  - "@next/eslint-plugin-next"
  - eslint-plugin-react-hooks

allowBuilds:
  sharp: false
  simple-git-hooks@2.13.1: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - ts-api-utils@2.4.0

trustPolicyExclude:
  - eslint-import-resolver-typescript@3.10.1
  - semver@6.3.1
  - tailwindcss@3.4.18
