name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oBusk/action-pnpm-setup@v1

      - name: Validate formatting
        run: pnpm run prettier

      - name: Validate types
        run: pnpm run typecheck

      - name: Determine npm dist-tag
        id: dist-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"-"* ]]; then
            echo "TAG=next" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish package
        run: pnpm publish --tag ${{ steps.dist-tag.outputs.TAG }} --no-git-checks
