name: Publish canary
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm
      - run: npm ci
      - name: Get previous canary version
        id: previous-version
        run: echo "::set-output name=version::$(npm show @obusk/eslint-config-next version --tag canary)"
      - name: Increment canary version
        id: increment-version
        run: |
          previous_version=${{ steps.previous-version.outputs.version }}
          # Extract the base version and the canary identifier
          base_version=$(echo $previous_version | cut -d'-' -f 1)
          canary_identifier=$(echo $previous_version | cut -d'.' -f 4)
          canary_identifier=$((canary_identifier + 1))
          new_version="${base_version}-canary.${canary_identifier}"
          echo "New version: $new_version"
          echo "::set-output name=new_version::$new_version"
      - name: Set new version
        run: npm version ${{ steps.increment-version.outputs.new_version }} --no-git-tag-version
      - run: npm publish --provenance --tag canary --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
