name: Publish release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    name: "Publish release"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
          registry-url: "https://registry.npmjs.org/"
      - name: Install latest npm
        run: npm install -g npm
      - name: Install dependencies
        run: npm ci
      - name: Validate formatting
        run: npm run prettier
      - name: Determine npm dist-tag
        id: dist-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"-"* ]]; then
            echo "TAG=next" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi
      - name: Publish package
        run: npm publish --provenance --tag ${{ steps.dist-tag.outputs.TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
