name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Validate formatting
        run: pnpm run prettier

      - name: Determine npm dist-tag
        id: dist-tag
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"-"* ]]; then
            echo "TAG=next" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish package
        run: pnpm publish --tag ${{ steps.dist-tag.outputs.TAG }} --no-git-checks
