name: Publish canary
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          registry-url: "https://registry.npmjs.org"
      - run: npm install -g npm
      - run: npm ci
      - name: Get previous canary version
        id: previous-version
        run: |
          echo "::set-output name=releaseVersion::$(npm show @obusk/eslint-config-next version)"
          echo "::set-output name=version::$(npm show @obusk/eslint-config-next version --tag canary)"
      - name: Increment canary version
        id: increment-version
        run: |
          release_version=${{ steps.previous-version.outputs.releaseVersion }}
          previous_version=${{ steps.previous-version.outputs.version }}
          # check if release_version is higher than previous_version using semver
          if [ "$(npx semver $release_version -r $previous_version)" = "$release_version" ]; then
            echo "Release version is higher than previous canary version"
            new_version=$release_version
          else
            echo "Release version is not higher than previous canary version"
            new_version=$(npx semver $previous_version -i prerelease --preid canary)
          fi
      - name: Set new version
        run: npm version ${{ steps.increment-version.outputs.new_version }} --no-git-tag-version
      - run: npm publish --provenance --tag canary --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
