name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5
        with:
          path: config

      - name: Checkout test repository
        uses: actions/checkout@v5
        with:
          repository: oBusk/npm-diff.app
          path: test

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./config/package.json

      - uses: actions/setup-node@v5
        with:
          node-version-file: ./config/package.json
          cache: pnpm
          cache-dependency-path: "*/pnpm-lock.yaml"

      - working-directory: config
        run: pnpm install --frozen-lockfile

      - working-directory: config
        run: pnpm link

      - working-directory: test
        run: pnpm link @obusk/eslint-config-next

      - working-directory: test
        name: Run linting inside test
        run: pnpm exec next lint
