name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: config

      - name: Checkout test repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: oBusk/warcraftlogs-search
          path: test

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: true
          package_json_file: ./config/package.json

      - working-directory: config
        run: pnpm install --frozen-lockfile

      - working-directory: config
        run: pnpm pack

      - working-directory: test
        run: pnpm install

      - working-directory: test
        run: pnpm install -D ../config/*.tgz

      - working-directory: test
        name: Run linting inside test
        run: pnpm run lint
