name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          path: config

      - name: Checkout test repository
        uses: actions/checkout@v4
        with:
          repository: oBusk/npm-diff.app
          path: test

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./test/package.json
          cache: npm
          cache-dependency-path: "*/package-lock.json"

      - working-directory: config
        run: npm ci

      - working-directory: config
        run: npm link

      - working-directory: test
        run: npm link @obusk/eslint-config-next

      - working-directory: test
        name: Run linting inside test
        run: ./node_modules/.bin/next lint
