name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: config

      - name: Checkout test repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: oBusk/warcraftlogs-search
          path: test

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: true
          package_json_file: ./config/package.json

      - working-directory: config
        run: pnpm install --frozen-lockfile

      - working-directory: config
        run: pnpm pack

      - working-directory: test
        run: pnpm install

      - working-directory: test
        run: pnpm install -D ../config/*.tgz

      - working-directory: test
        name: Run linting inside test
        run: pnpm run lint
