name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5
        with:
          path: config

      - name: Checkout test repository
        uses: actions/checkout@v5
        with:
          repository: oBusk/warcraftlogs-search
          path: test

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: ./config/package.json

      - working-directory: config
        run: pnpm install --frozen-lockfile

      - working-directory: config
        run: pnpm pack

      - working-directory: test
        run: npm install

      - working-directory: test
        run: npm install -D ../config/*.tgz

      - working-directory: test
        name: Run linting inside test
        run: npm run lint
