name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      CI: true
    steps:
      - name: Checkout this repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: config

      - name: Checkout test repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: oBusk/warcraftlogs-search
          path: test

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          run_install: true
          package_json_file: ./config/package.json

      - working-directory: config
        run: pnpm install --frozen-lockfile

      - working-directory: config
        run: pnpm pack

      - working-directory: test
        run: pnpm install

      - working-directory: test
        run: pnpm install -D ../config/*.tgz

      - working-directory: test
        name: Run linting inside test
        run: pnpm run lint
